export const fakeData = [
    {
        id: 1,
        name: "fake_name",
        brand: "fake_brand",
        price: 20,
        image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        discount: true,
        discountValue: 10,
        isNovelty: false,
        forOrder: true,
    },
    {
        id: 2,
        name: "fake_name",
        brand: "fake_brand",
        price: 20,
        image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        isNovelty: true,
        forOrder: true,
    },
    {
        id: 3,
        name: "fake_name",
        brand: "fake_brand",
        price: 20,
        image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        isNovelty: false,
        forOrder: true,
    },
    {
        id: 4,
        name: "fake_name",
        brand: "fake_brand",
        price: 20,
        image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        isNovelty: true,
        forOrder: true,
    },
    {
        id: 5,
        name: "fake_name",
        brand: "fake_brand",
        price: 20,
        image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        isNovelty: false,
        forOrder: true,
    },
    {
        id: 6,
        name: "fake_name",
        brand: "fake_brand",
        price: 20,
        image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        isNovelty: true,
        forOrder: true,
    },
    {
        id: 7,
        name: "fake_name",
        brand: "fake_brand",
        price: 20,
        image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        isNovelty: true,
        forOrder: true,
    },
    {
        id: 8,
        name: "fake_name",
        brand: "fake_brand",
        price: 20,
        image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        isNovelty: true,
        forOrder: false,
    },
    {
        id: 9,
        name: "fake_name",
        brand: "fake_brand",
        price: 20,
        image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        isNovelty: false,
        forOrder: false,
    },
]